### ISSUE TITLE
Payment system not functioning

### ISSUE THREAD

**Issue by HansHagberg** [DeepBrainChain/deepbrainchain-release#4]
Machine suppliers do not get paid for compute time.
Skynet has been online for 2 months at the time of writing. There have been a few reported tasks during this time. However, no payment has been observed. This is the most serious type of defect possible for an incentive based distributed compute system. This also means the DBC token has no utility and the market valuation will go towards zero.

**Comment by brightzhang2018** [comment]
a little bit negative viewpoint.haha.  we have the incentive plan for skynet. if you don't get it , pleae provide your info and let me check .

**Comment by zer0spacee** [comment]
> a little bit negative viewpoint.haha. we have the incentive plan for skynet. if you don't get it , pleae provide your info and let me check .

Bright, Hans is pointing out that the payment mechanism (how the platform is technically configured to appropriately pay compute nodes for their services from the customers), which is a fundamental benefit of AI + Blockchain, has not been proven, as all transactions are occurring manually, as proven by your request "please provide your info and let me check".

**Comment by brightzhang2018** [comment]
Hi zer0spacee. what I mean here is the payment mechanism is working fine. which means  if the machine is running task, the AI user will pay the benefit. if the machine is idle, based on skynet plan, the provider will get the allowance. If someone didn't get it , i can try to check if something wrong there.

**Comment by HansHagberg** [comment]
This can't be correct.
Not a single payment has been reported by anyone in Skynet.
Almost all of us have had some tasks running. This includes the crypto miner tasks that infiltrated the nodes for a few days. So - what is the evidence that the payment system is functional?
